name: OPENTIX LINE Test

on:
  schedule:

    - cron: "0 * * * *"
  
  workflow_dispatch:

jobs:

  test:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v6

        with:
          python-version: "3.12"


      - name: Install packages
        run: |
          pip install -r requirements.txt
          playwright install chromium


      - name: Run Python

        env:

          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}

          LINE_USER: ${{ secrets.LINE_USER }}

        run: |
          python main.py
          
      - name: Save status
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add status.json
          git commit -m "Update ticket status" || echo "No changes to commit"
          git push
